const ADD_TERMINAL_MODAL_WINDOW_OPEN = 'ADD_TERMINAL_MODAL_WINDOW_OPEN';
const ADD_TERMINAL_MODAL_WINDOW_CLOSE = 'ADD_TERMINAL_MODAL_WINDOW_CLOSE';

const START_EXPORT_TERMINALS = 'START_EXPORT_TERMINALS';
const SUCCESS_EXPORT_TERMINALS = 'SUCCESS_EXPORT_TERMINALS';
const ERROR_EXPORT_TERMINALS = 'ERROR_EXPORT_TERMINALS';

exports.ADD_TERMINAL_MODAL_WINDOW_OPEN = ADD_TERMINAL_MODAL_WINDOW_OPEN;
exports.ADD_TERMINAL_MODAL_WINDOW_CLOSE = ADD_TERMINAL_MODAL_WINDOW_CLOSE;

exports.START_EXPORT_TERMINALS = START_EXPORT_TERMINALS;
exports.SUCCESS_EXPORT_TERMINALS = SUCCESS_EXPORT_TERMINALS;
exports.ERROR_EXPORT_TERMINALS = ERROR_EXPORT_TERMINALS;
