const SPINNER_SHOW = 'SHOW_LOADING_SPINNER';
const SPINNER_LOADING_SUCCESS = 'LOADING_SUCCESS_SPINNER';
const SPINNER_LOADING_ERROR = 'LOADING_ERROR_SPINNER';
const SPINNER_HIDE = 'HIDE_LOADING_SPINNER';

exports.SPINNER_SHOW = SPINNER_SHOW;
exports.SPINNER_LOADING_SUCCESS = SPINNER_LOADING_SUCCESS;
exports.SPINNER_LOADING_ERROR = SPINNER_LOADING_ERROR;
exports.SPINNER_HIDE = SPINNER_HIDE;
