const ADD_TERMINAL_INSTANCE = 'ADD_TERMINAL_INSTANCE';
const SELECT_TERMINAL_INSTANCE = 'SELECT_TERMINAL_INSTANCE';
const IMPORT_TERMINALS = 'IMPORT_TERMINAL_INSTANCES';
const RELOAD_TERMINAL = 'RELOAD_TERMINAL_INSTANCE';

exports.ADD_TERMINAL_INSTANCE = ADD_TERMINAL_INSTANCE;
exports.SELECT_TERMINAL_INSTANCE = SELECT_TERMINAL_INSTANCE;
exports.IMPORT_TERMINALS = IMPORT_TERMINALS;
exports.RELOAD_TERMINAL = RELOAD_TERMINAL;
