const ADD_TERMINAL_INSTANCE = 'ADD_TERMINAL_INSTANCE';
const SELECT_TERMINAL_INSTANCE = 'SELECT_TERMINAL_INSTANCE';
const IMPORT_TERMINALS = 'IMPORT_TERMINAL_INSTANCES';
const RELOAD_TERMINAL_INSTANCE = 'RELOAD_TERMINAL_INSTANCE';
const DELETE_TERMINAL_INSTANCE = 'DELETE_TERMINAL INSTANCE';
const MOVE_RIGHT_TERMINAL_INSTANCE = 'MOVE_RIGHT_TERMINAL_INSTANCE';
const MOVE_LEFT_TERMINAL_INSTANCE = 'MOVE_LEFT_TERMINAL_INSTANCE';

exports.ADD_TERMINAL_INSTANCE = ADD_TERMINAL_INSTANCE;
exports.SELECT_TERMINAL_INSTANCE = SELECT_TERMINAL_INSTANCE;
exports.IMPORT_TERMINALS = IMPORT_TERMINALS;
exports.RELOAD_TERMINAL_INSTANCE = RELOAD_TERMINAL_INSTANCE;
exports.DELETE_TERMINAL_INSTANCE = DELETE_TERMINAL_INSTANCE;
exports.MOVE_RIGHT_TERMINAL_INSTANCE = MOVE_RIGHT_TERMINAL_INSTANCE;
exports.MOVE_LEFT_TERMINAL_INSTANCE = MOVE_LEFT_TERMINAL_INSTANCE;
