const ADD_NEW_TERMINAL_INSTANCE = 'ADD_NEW_TERMINAL_INSTANCE';
const EDIT_EXISTING_TERMINAL_INSTANCE = 'EDIT_EXISTING_TERMINAL_INSTANCE';

exports.ADD_NEW_TERMINAL_INSTANCE = ADD_NEW_TERMINAL_INSTANCE;
exports.EDIT_EXISTING_TERMINAL_INSTANCE = EDIT_EXISTING_TERMINAL_INSTANCE;
