const ADD_TERMINAL_INSTANCE = 'ADD_TERMINAL_INSTANCE';
const SELECT_TERMINAL_INSTANCE = 'SELECT_TERMINAL_INSTANCE';
const TERMINAL_DONE_INITIALIZATION = 'TERMINAL_DONE_INITIALIZATION';

exports.ADD_TERMINAL_INSTANCE = ADD_TERMINAL_INSTANCE;
exports.SELECT_TERMINAL_INSTANCE = SELECT_TERMINAL_INSTANCE;
exports.TERMINAL_DONE_INITIALIZATION = TERMINAL_DONE_INITIALIZATION;
